language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

sudo: false

env:
    - SYMFONY_VERSION="~2.3.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="~2.5.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="~2.6.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="~2.7.0" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"
    - SYMFONY_VERSION="2.8.x-dev" DOCTRINE_VERSION=">=2.2.3,<2.5-dev"

before_script:
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
    - composer require --no-update "doctrine/orm":"${DOCTRINE_VERSION}"
    - composer install --prefer-source --ignore-platform-reqs

script: vendor/bin/phpunit
